export const bookMockResponse = {
  id: 7,
  name: 'Harry Potter and the Deathly Hallows',
  authorId: 1,
  noOfPages: 607,
  dateOfPublishing: '21 July 2007',
  illustrator: 'Cliff Wright',
  description:
    "Harry has been burdened with a dark, dangerous and seemingly impossible task: that of locating and destroying Voldemort's remaining Horcruxes. Never has Harry felt so alone, or faced a future so full of shadows. But Harry must somehow find within himself the strength to complete the task he has been given. He must leave the warmth, safety and companionship of The Burrow and follow without fear or hesitation the inexorable path laid out for him...\n\n      In this final, seventh installment of the Harry Potter series, J.K. Rowling unveils in spectacular fashion the answers to the many questions that have been so eagerly awaited.",
  img: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Harry_Potter_and_the_Deathly_Hallows.jpg',
  price: 28,
  genre: 'Fiction',
  publisher: 'Bloomsbury',
  createdAt: '2022-10-26T03:53:07.954Z',
  updatedAt: '2022-10-26T03:53:07.954Z',
  author: {
    id: 1,
    name: 'J. K. Rowling',
    bornOn: '31 July 1965',
    spouce: 'Neil Murray',
    children: 3,
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
    bornIn: 'USA',
    createdAt: '2022-10-26T03:53:07.866Z',
    updatedAt: '2022-10-26T03:53:07.866Z',
  },
};

export const bookListMockResponse = [
  {
    id: 7,
    name: 'Harry Potter and the Deathly Hallows',
    authorId: 1,
    noOfPages: 607,
    dateOfPublishing: '21 July 2007',
    illustrator: 'Cliff Wright',
    description:
      "Harry has been burdened with a dark, dangerous and seemingly impossible task: that of locating and destroying Voldemort's remaining Horcruxes. Never has Harry felt so alone, or faced a future so full of shadows. But Harry must somehow find within himself the strength to complete the task he has been given. He must leave the warmth, safety and companionship of The Burrow and follow without fear or hesitation the inexorable path laid out for him...\n\n      In this final, seventh installment of the Harry Potter series, J.K. Rowling unveils in spectacular fashion the answers to the many questions that have been so eagerly awaited.",
    img: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Harry_Potter_and_the_Deathly_Hallows.jpg',
    price: 28,
    genre: 'Fiction',
    publisher: 'Bloomsbury',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 1,
      name: 'J. K. Rowling',
      bornOn: '31 July 1965',
      spouce: 'Neil Murray',
      children: 3,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
      bornIn: 'USA',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 6,
    name: 'Harry Potter and the Half-Blood Prince',
    authorId: 1,
    noOfPages: 607,
    dateOfPublishing: '16 July 2005',
    illustrator: 'Cliff Wright',
    description:
      "It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster was in a fierce one-to-one duel with Lord Voldemort, and Harry can't quite believe that Professor Dumbledore will actually appear at the Dursleys' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks' time? Harry's sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine...",
    img: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Harry_Potter_and_the_Half-Blood_Prince_cover.png',
    price: 22,
    genre: 'Fiction',
    publisher: 'Bloomsbury',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 1,
      name: 'J. K. Rowling',
      bornOn: '31 July 1965',
      spouce: 'Neil Murray',
      children: 3,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
      bornIn: 'USA',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 5,
    name: 'Harry Potter and the Order of the Phoenix',
    authorId: 1,
    noOfPages: 766,
    dateOfPublishing: '21 June 2003',
    illustrator: 'Cliff Wright',
    description:
      'Harry Potter is about to start his fifth year at Hogwarts School of Witchcraft and Wizardry. Unlike most schoolboys, Harry never enjoys his summer holidays, but this summer is even worse than usual. The Dursleys, of course, are making his life a misery, but even his best friends, Ron and Hermione, seem to be neglecting him.\n\n      Harry has had enough. He is beginning to think he must do something, anything, to change his situation, when the summer holidays come to an end in a very dramatic fashion. What Harry is about to discover in his new year at Hogwarts will turn his world upside down...\n      ',
    img: 'https://upload.wikimedia.org/wikipedia/en/7/70/Harry_Potter_and_the_Order_of_the_Phoenix.jpg',
    price: 28,
    genre: 'Fiction',
    publisher: 'Bloomsbury',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 1,
      name: 'J. K. Rowling',
      bornOn: '31 July 1965',
      spouce: 'Neil Murray',
      children: 3,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
      bornIn: 'USA',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 4,
    name: 'Harry Potter and Goblet of Fire',
    authorId: 1,
    noOfPages: 636,
    dateOfPublishing: '8 July 2000',
    illustrator: 'Cliff Wright',
    description:
      'It is the summer holidays and soon Harry Potter will be starting his fourth year at Hogwarts School of Witchcraft and Wizardry. Harry is counting the days: there are new spells to be learnt, more Quidditch to be played, and Hogwarts castle to continue exploring. But Harry needs to be careful - there are unexpected dangers lurking...',
    img: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Harry_Potter_and_the_Goblet_of_Fire_cover.png',
    price: 35,
    genre: 'Fiction',
    publisher: 'Bloomsbury',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 1,
      name: 'J. K. Rowling',
      bornOn: '31 July 1965',
      spouce: 'Neil Murray',
      children: 3,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
      bornIn: 'USA',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 3,
    name: 'Harry Potter and the Prisoner of Azkaban',
    authorId: 1,
    noOfPages: 317,
    dateOfPublishing: '8 July 1999',
    illustrator: 'Cliff Wright',
    description:
      "Harry Potter, along with his best friends, Ron and Hermione, is about to start his third year at Hogwarts School of Witchcraft and Wizardry. Harry can't wait to get back to school after the summer holidays. (Who wouldn't if they lived with the horrible Dursleys?) But when Harry gets to Hogwarts, the atmosphere is tense. There's an escaped mass murderer on the loose, and the sinister prison guards of Azkaban have been called in to guard the school...\n      ",
    img: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Harry_Potter_and_the_Prisoner_of_Azkaban.jpg',
    price: 35,
    genre: 'Fiction',
    publisher: 'Bloomsbury',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 1,
      name: 'J. K. Rowling',
      bornOn: '31 July 1965',
      spouce: 'Neil Murray',
      children: 3,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
      bornIn: 'USA',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 2,
    name: 'Harry Potter and the Chamber of Secrets',
    authorId: 1,
    noOfPages: 251,
    dateOfPublishing: '2 July 1998',
    illustrator: 'Cliff Wright',
    description:
      'ver since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike.\n\n      And strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!',
    img: 'https://upload.wikimedia.org/wikipedia/en/5/5c/Harry_Potter_and_the_Chamber_of_Secrets.jpg',
    price: 40,
    genre: 'Fiction',
    publisher: 'Bloomsbury',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 1,
      name: 'J. K. Rowling',
      bornOn: '31 July 1965',
      spouce: 'Neil Murray',
      children: 3,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
      bornIn: 'USA',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 1,
    name: "Harry Potter and the Philosopher's Stone",
    authorId: 1,
    noOfPages: 223,
    dateOfPublishing: '26 June 1997',
    illustrator: 'Cliff Wright',
    description:
      'Harry Potter thinks he is an ordinary boy - until he is rescued by an owl, taken to Hogwarts School of Witchcraft and Wizardry, learns to play Quidditch and does battle in a deadly duel. The Reason ... HARRY POTTER IS A WIZARD!',
    img: 'https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg',
    price: 30,
    genre: 'Fiction',
    publisher: 'Bloomsbury',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 1,
      name: 'J. K. Rowling',
      bornOn: '31 July 1965',
      spouce: 'Neil Murray',
      children: 3,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/440px-J._K._Rowling_2010.jpg',
      bornIn: 'USA',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 9,
    name: 'Only time will tell',
    authorId: 2,
    noOfPages: 400,
    dateOfPublishing: 'March 2011',
    illustrator: null,
    description:
      'The epic tale of Harry Clifton’s life begins in 1920, with the words “I was told that my father was killed in the war.” A dock worker in Bristol, Harry never knew his father, but he learns about life on the docks from his uncle, who expects Harry to join him at the shipyard once he’s left school. But then an unexpected gift wins him a scholarship to an exclusive boys’ school, and his life will never be the same again.\n      As he enters into adulthood, Harry finally learns how his father really died, but the awful truth only leads him to question, was he even his father? Is he the son of Arthur Clifton, a stevedore who spent his whole life on the docks, or the firstborn son of a scion of West Country society, whose family owns a shipping line?\n      \n      This introductory novel in Archer’s ambitious series The Clifton Chronicles includes a cast of colorful characters and takes us from the ravages of the Great War to the outbreak of the Second World War, when Harry must decide whether to take up a place at Oxford or join the navy and go to war with Hitler’s Germany. From the docks of working-class England to the bustling streets of 1940 New York City, Only Time Will Tell takes readers on a journey through to future volumes, which will bring to life one hundred years of recent history to reveal a family story that neither the reader nor Harry Clifton himself could ever have imagined.',
    img: 'https://upload.wikimedia.org/wikipedia/en/f/fd/OnlyTimeWillTell.jpg',
    price: 27,
    genre: 'Fiction',
    publisher: 'Macmillan',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 2,
      name: 'Jeffrey Archer',
      bornOn: '15 April 1940',
      spouce: 'Mary Weeden',
      children: 2,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Jeffrey_Archer_%40_Oslo_bokfestival_2012_4.jpg/440px-Jeffrey_Archer_%40_Oslo_bokfestival_2012_4.jpg',
      bornIn: 'England',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
  {
    id: 8,
    name: 'Kane and Abel',
    authorId: 2,
    noOfPages: 512,
    dateOfPublishing: '1979',
    illustrator: null,
    description:
      'Born on the same day near the turn of the century on opposite sides of the world, both men are brought together by fate and the quest of a dream. These two men -- ambitious, powerful, ruthless -- are locked in a relentless struggle to build an empire, fuelled by their all-consuming hatred. Over 60 years and three generations, through war, marriage, fortune, and disaster, Kane and Abel battle for the success and triumph that only one man can have.',
    img: 'https://upload.wikimedia.org/wikipedia/en/f/f3/KaneAndAbel.jpg',
    price: 24,
    genre: 'Fiction',
    publisher: 'Hodder & Stoughton',
    createdAt: '2022-10-26T03:53:07.954Z',
    updatedAt: '2022-10-26T03:53:07.954Z',
    author: {
      id: 2,
      name: 'Jeffrey Archer',
      bornOn: '15 April 1940',
      spouce: 'Mary Weeden',
      children: 2,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Jeffrey_Archer_%40_Oslo_bokfestival_2012_4.jpg/440px-Jeffrey_Archer_%40_Oslo_bokfestival_2012_4.jpg',
      bornIn: 'England',
      createdAt: '2022-10-26T03:53:07.866Z',
      updatedAt: '2022-10-26T03:53:07.866Z',
    },
  },
];

export const bookAvgRatingMockResponse = {
  bookId: 1,
  avgRating: '5.0000000000000000',
};
